version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000

  # Alias dla wykonywania lintera
  frontend-lint:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    profiles:
      - lint
    container_name: react-frontend-lint
    command: npm run lint
    networks:
      - app-network

  # solana:
  #   build:
  #     context: ./solana
  #   platform: linux/amd64
  #   volumes:
  #     - ./solana:/app
  #   container_name: solana-anchor
  #   ports:
  #     - "8899:8899"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
